const W = 10, H = 10, SEGMENTS = 10, TILE = 60, WORLD_W = W * SEGMENTS * TILE;
const TYPES = { spawn:{label:'Spawn', color:'#65d6ff'}, block:{label:'Block', color:'#d5d9cf'}, checkpoint:{label:'Checkpoint', color:'#ffc857'}, spikes:{label:'Spikes', color:'#ff5c77'}, goal:{label:'Goal', color:'#ccff55'}, erase:{label:'Eraser', color:'#667066'} };
const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
let level = loadLevel(), segment = 0, mode = 'edit', tool = 'block', drawing = false, keys = new Set();
const tuning = { jumpHeight: 9, apexGravity: 7 };
let player = { x: 95, y: 300, w:34, h:46, vx:0, vy:0, grounded:false, lastGrounded:0, lastJumpPress:-Infinity, checkpoint:null };
let last = performance.now(), won = false;
function blank() { return Array.from({length: W * H * SEGMENTS}, () => null); }
const SHARE_CODES = { null:'n', spawn:'s', block:'b', checkpoint:'c', spikes:'p', goal:'g' };
const SHARE_TYPES = Object.fromEntries(Object.entries(SHARE_CODES).map(([type,code])=>[code,type==='null'?null:type]));
function encodeLevel(value) { let result='v2.'; for(let i=0;i<value.length;){let length=1;while(i+length<value.length&&value[i+length]===value[i])length++;result+=`${i?',':''}${SHARE_CODES[value[i]]}${length.toString(36)}`;i+=length;} return result; }
function decodeLevel(value) { try { if(value.startsWith('v2.')){const result=[];for(const token of value.slice(3).split(',')){const type=SHARE_TYPES[token[0]],count=parseInt(token.slice(1),36);if(type===undefined||!Number.isInteger(count)||count<1)return null;result.push(...Array(count).fill(type));}return result.length===1000?result:null;} const padded=value.replaceAll('-','+').replaceAll('_','/')+'==='.slice((value.length+3)%4); const parsed=JSON.parse(atob(padded)); return Array.isArray(parsed) && parsed.length===1000 ? parsed : null; } catch { return null; } }
function loadLevel() { const shared=location.hash.match(/^#level=([^&]+)/); const fromUrl=shared && decodeLevel(shared[1]); if(fromUrl) return fromUrl; try { const v = JSON.parse(localStorage.minimalLevel || 'null'); return Array.isArray(v) && v.length === 1000 ? v : blank(); } catch { return blank(); } }
function save() { localStorage.minimalLevel = JSON.stringify(level); }
function index(x,y) { return y * W * SEGMENTS + ((x % (W * SEGMENTS) + W * SEGMENTS) % (W * SEGMENTS)); }
function get(x,y) { return y < 0 || y >= H ? null : level[index(x,y)]; }
function set(x,y,v) { level[index(x,y)] = v; save(); }
function populatePalette() { const el = document.querySelector('#palette'); el.replaceChildren(); Object.entries(TYPES).forEach(([id, spec]) => { const b=document.createElement('button'); b.className='tool'; b.dataset.tool=id; b.innerHTML=`<i class="swatch" style="background:${spec.color}"></i>${spec.label}`; b.onclick=()=>{tool=id; populatePalette();}; el.append(b); }); document.querySelector(`[data-tool="${tool}"]`).classList.add('active'); }
function setMode(next) { mode=next; document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode)); document.querySelector('#editorPanel').style.visibility=mode==='edit'?'visible':'hidden'; if(mode==='play') resetPlayer(); else won=false; document.querySelector('#status').textContent=mode==='edit'?'Edit mode · select an object and draw your level.':'Play mode · segments loop endlessly at either side.'; }
function resetPlayer() { const s=level.findIndex(v=>v==='spawn'); const x=s >= 0 ? s % (W*SEGMENTS) : 1, y=s >= 0 ? Math.floor(s/(W*SEGMENTS)) : 4; player={x:x*TILE+13,y:y*TILE+5,w:34,h:46,vx:0,vy:0,grounded:false,lastGrounded:0,lastJumpPress:-Infinity,checkpoint:null}; won=false; segment=Math.floor(x/W); }
function cellFromEvent(e) { const r=canvas.getBoundingClientRect(), localX=Math.floor((e.clientX-r.left)/r.width*W), y=Math.floor((e.clientY-r.top)/r.height*H); return {localX, x:segment*W+localX, y}; }
function paint(e) { if(mode!=='edit') return; const c=cellFromEvent(e); if(c.localX<0||c.localX>=W||c.y<0||c.y>=H)return; if(tool==='spawn') { level=level.map(v=>v==='spawn'?null:v); } set(c.x,c.y,tool==='erase'?null:tool); }
canvas.addEventListener('pointerdown', e=>{drawing=true; canvas.setPointerCapture(e.pointerId); paint(e);}); canvas.addEventListener('pointermove',e=>{if(drawing)paint(e);}); canvas.addEventListener('pointerup',()=>drawing=false);
function drawTile(type, px, py) { if(!type)return; const c=TYPES[type].color; if(type==='spikes') { ctx.fillStyle=c; for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(px+i*20,py+59);ctx.lineTo(px+10+i*20,py+12);ctx.lineTo(px+20+i*20,py+59);ctx.fill();} return; } ctx.fillStyle=c; if(type==='checkpoint'){ctx.fillRect(px+28,py+8,4,50);ctx.fillRect(px+32,py+8,22,15);} else if(type==='goal'){ctx.fillRect(px+28,py+7,4,52);ctx.beginPath();ctx.arc(px+30,py+12,11,0,Math.PI*2);ctx.fill();} else if(type==='spawn'){ctx.beginPath();ctx.arc(px+30,py+30,15,0,Math.PI*2);ctx.fill();} else ctx.fillRect(px+4,py+4,52,52); }
function render() { ctx.clearRect(0,0,600,600); ctx.strokeStyle='#293028';ctx.lineWidth=1; for(let i=0;i<=10;i++){ctx.beginPath();ctx.moveTo(i*TILE,0);ctx.lineTo(i*TILE,600);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*TILE);ctx.lineTo(600,i*TILE);ctx.stroke();} for(let y=0;y<H;y++)for(let x=0;x<W;x++)drawTile(get(segment*W+x,y),x*TILE,y*TILE); if(mode==='play'){let localX=((player.x%WORLD_W)+WORLD_W)%WORLD_W-segment*W*TILE; if(localX>canvas.width)localX-=WORLD_W; if(localX<-canvas.width)localX+=WORLD_W; ctx.save();ctx.beginPath();ctx.rect(0,0,canvas.width,canvas.height);ctx.clip();ctx.fillStyle='#f7f9f2';ctx.fillRect(localX,player.y,player.w,player.h);ctx.restore(); } if(won){ctx.fillStyle='rgba(12,14,11,.75)';ctx.fillRect(0,0,600,600);ctx.fillStyle='#ccff55';ctx.font='700 36px system-ui';ctx.textAlign='center';ctx.fillText('LEVEL COMPLETE',300,295);ctx.textAlign='left';} document.querySelector('#segmentLabel').textContent=`Segment ${segment+1} / 10`; }
function solidAt(px,py) { return get(Math.floor(px/TILE),Math.floor(py/TILE))==='block'; }
function jumpVelocity() { return -(280 + tuning.jumpHeight * 46); }
function fallingGravity() { return 550 + tuning.apexGravity * 180; }
function overlapType(type) { const l=Math.floor(player.x/TILE), r=Math.floor((player.x+player.w-1)/TILE), t=Math.floor(player.y/TILE), b=Math.floor((player.y+player.h-1)/TILE); for(let y=t;y<=b;y++)for(let x=l;x<=r;x++)if(get(x,y)===type)return {x,y}; return null; }
function respawn() { if(!player.checkpoint) return resetPlayer(); player.x=player.checkpoint.x*TILE+13; player.y=player.checkpoint.y*TILE-player.h; player.vx=0; player.vy=0; player.grounded=false; }
function update(dt, now) { if(mode!=='play'||won)return; const left=keys.has('ArrowLeft')||keys.has('KeyA'), right=keys.has('ArrowRight')||keys.has('KeyD'); player.vx=(right-left)*250; player.vy+=(player.vy < 0 ? 1250 : fallingGravity())*dt; const oldX=player.x; player.x+=player.vx*dt; if(player.vx){const edge=player.vx>0?player.x+player.w:player.x; if(solidAt(edge,player.y+5)||solidAt(edge,player.y+player.h-5)){player.x=oldX;}} player.y+=player.vy*dt; player.grounded=false; if(player.vy>=0){const foot=player.y+player.h; if(solidAt(player.x+4,foot)||solidAt(player.x+player.w-4,foot)){player.y=Math.floor(foot/TILE)*TILE-player.h;player.vy=0;player.grounded=true;player.lastGrounded=now;}} else {const head=player.y;if(solidAt(player.x+4,head)||solidAt(player.x+player.w-4,head)){player.y=Math.floor(head/TILE+1)*TILE;player.vy=0;}} if(player.grounded&&now-player.lastJumpPress<=100){player.vy=jumpVelocity();player.grounded=false;player.lastJumpPress=-Infinity;} if(player.y>650) respawn(); const cp=overlapType('checkpoint');if(cp)player.checkpoint=cp; if(overlapType('spikes'))respawn(); if(overlapType('goal'))won=true; const wrappedCenter=((player.x+player.w/2)%WORLD_W+WORLD_W)%WORLD_W; segment=Math.floor(wrappedCenter/(W*TILE)); }
function loop(now) { const dt=Math.min(.033,(now-last)/1000);last=now;update(dt,now);render();requestAnimationFrame(loop); }
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode)); document.querySelector('#prevSegment').onclick=()=>segment=(segment+SEGMENTS-1)%SEGMENTS;document.querySelector('#nextSegment').onclick=()=>segment=(segment+1)%SEGMENTS;document.querySelector('#clearSegment').onclick=()=>{for(let y=0;y<H;y++)for(let x=0;x<W;x++)set(segment*W+x,y,null);};document.querySelector('#resetLevel').onclick=()=>{level=blank();save();resetPlayer();};
document.querySelector('#shareLevel').onclick=async()=>{const link=`${location.href.split('#')[0]}#level=${encodeLevel(level)}`; try { await navigator.clipboard.writeText(link); document.querySelector('#status').textContent='Share link copied to your clipboard.'; } catch { window.prompt('Copy this level link:',link); }};
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','Space','KeyA','KeyD','KeyW'].includes(e.code))e.preventDefault();keys.add(e.code);if(mode==='edit'&&(e.code==='ArrowLeft'||e.code==='KeyA'))segment=(segment+9)%10;if(mode==='edit'&&(e.code==='ArrowRight'||e.code==='KeyD'))segment=(segment+1)%10;if(mode==='play'&&['ArrowUp','Space','KeyW'].includes(e.code)&&!e.repeat){const now=performance.now();player.lastJumpPress=now;if(player.grounded||now-player.lastGrounded<=50){player.vy=jumpVelocity();player.grounded=false;player.lastJumpPress=-Infinity;}}});window.addEventListener('keyup',e=>keys.delete(e.code));
populatePalette();setMode('edit');requestAnimationFrame(loop);
